#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.chef.io/api/v1'

cookbook 'opsworks-resque', github: 'pedroaxl/opsworks-resque'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
